#!/bin/bash
set -e

REGISTRY_PORT=21504

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

images=(
	'quay.io/coreos/hyperkube:v1.5.1_coreos.0'
  'gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0'
	'gcr.io/google_containers/kubedns-amd64:1.9'
	'gcr.io/google_containers/kube-dnsmasq-amd64:1.4'
  'gcr.io/google_containers/dnsmasq-metrics-amd64:1.0'
  'gcr.io/google_containers/exechealthz-amd64:1.2'
	'gcr.io/google_containers/heapster:v1.2.0'
	'gcr.io/google_containers/addon-resizer:1.6'
	'gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0'
	'gcr.io/google_containers/pause-amd64:3.0'
	)

for img in ${images[@]};
do
	echo "Pull $img"
	echo
	docker pull $img
    docker tag $img localhost:$REGISTRY_PORT/$(basename $img)
    echo "Push $(basename $img) into local registry"
    echo
    docker push localhost:$REGISTRY_PORT/$(basename $img)
    echo
done
